app/routes.php
<?php
Route::get('/', array('as' => 'users.main', 'uses' => 'HomeController@main'));

//Route::resource('/users', 'UsersController');
//Rutas de recurso usuario
Route::get('/users', array('as' => 'users.index', 'uses' => 'UsersController@index'));
Route::get('/users/create', array('as' => 'users.create', 'uses' => 'UsersController@create'));
Route::post('/users', array('as' => 'users.store', 'uses' => 'UsersController@store'));
Route::get('/users/{id}', array('as' => 'users.show', 'uses' => 'UsersController@show'))->where('id', '[0-9]+');
Route::get('/users/{id}/edit', array('as' => 'users.edit', 'uses' => 'UsersController@edit'))->where('id', '[0-9]+');
Route::put('/users/{id}', array('as' => 'users.update', 'uses' => 'UsersController@update'))->where('id', '[0-9]+');
Route::delete('/users/{id}', array('as' => 'users.delete', 'uses' => 'UsersController@delete'))->where('id', '[0-9]+');
Route::get('/users/login', array('as' => 'users.login', 'uses' => 'UsersController@login'));
Route::post('/users/auth', array('as' => 'users.auth', 'uses' => 'UsersController@auth'));
Route::get('/users/logout', array('as' => 'users.logout', 'uses' => 'UsersController@logout'));


Route::resource('contacts', 'ContactsController');

Route::post('/telephones/create', array('as' => 'telephones.create', 'uses' => 'TelephonesController@create'));
Route::post('/telephones', array('as' => 'telephones.store', 'uses' => 'TelephonesController@store'));

app/models/Telephones.php
<?php

use LaravelBook\Ardent\Ardent;

class Telephones extends Ardent {
	
	/**
	 * Ardent validation rules
	 *
	 * @var array
	 */
	public static $rules = array(
		'user_id'			=> 'required|exists:users,id',
		'label'				=> 'required|min:3|max:4',
		'telephone_number'	=> 'required|min:7|max:7'
	);

	public function contact()
	{
		return $this->belongsTo('Contact');
	}

}

app/controllers/TelephonesController.php
<?php

class TelephonesController extends BaseController {

	public function __construct()
	{
		$this->beforeFilter('auth');
	}

	public function index()
	{
		$telephones = telephones::with('telephones')->orderBy('created_at', 'desc')->get();

		return View::make('telephones.index', ['telephones' => $telephones]);
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /telephones/create
	 *
	 * @return Response
	 */
	public function create()
	{
		$telephones = new telephones();
		return View::make('telephones.create')->with('telephones', $telephones);
	}


	public function store()
	{
		//Si el usuario está logeado
		if(Auth::check())
		{
			//Guardamos el contact
			$telephones = new telephones();
			$telephones->label = Input::get('label');
			$telephones->telephones = Input::get('telephones');
			$telephones->contact_id = Auth::contact()->id;

			if($telephones->save())
			{
				return Redirect::route('telephones.show', [$telephones->id]);
			}
			else
			{
				return Redirect::route('telephones.create')->withInput()->withErrors($telephones->errors());
			}
		}
		else
		{
			//Redireccionamos hacia la pantalla de login
			return Redirect::route('users.login')->withError('Debes iniciar sesión.');
		}
	}

	/**
	 * Display the specified resource.
	 * GET /telephones/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$telephones = telephones::find($id);

		if($telephones)
		{
			return View::make('telephones.show', ['contact' => $contact]);
		}
		else
		{
			Throw new NotFoundHttpException;
		}
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /telephones/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$contact = Contact::find($id);

		if($contact)
		{
			return View::make('telephones.edit', array('contact' => $contact));
		}
		else
		{
			Throw new NotFoundHttpException;
		}
	}

	/**
	 * Update the specified resource in storage.
	 * PUT /telephones/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$telephones = Contact::find($id);

		if($telephones)
		{
			$telephones->name = Input::get('name');
			$telephones->last_name = Input::get('last_name');
			$telephones->email = Input::get('email');
			$telephones->addres = Input::get('addres');

			if($telephones->updateUniques())
			{
				return Redirect::route('telephones.show', array($telephones->id));
			}
			else
			{
				return Redirect::route('telephones.edit', array($id))->withErrors($telephones->errors());
			}
		}
		else
		{
			Throw new NotFoundHttpException;	
		}
	}

	/**
	 * Remove the specified resource from storage.
	 * DELETE /telephones/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}

}

app/views/telephones/_form.blade.php
	<div class="text-info">
	@if($errors->has('label'))
		@foreach($errors->get('label') as $error):
		{{Form::label('label', $error)}}
		@endforeach
	@endif
	 @if($errors->has('telephone_numer'))
		@foreach($errors->get('telephone_numer') as $error):
		{{Form::label('telephone_numer', $error)}}
		@endforeach
	@endif
	</div>
<fieldset>
	{{Form::text('label', $telephones->id, array('placeholder' => ''))}}
</fieldset>
<fieldset>
	{{Form::text('label', $telephones->label, array('placeholder' => '0416'))}}
</fieldset>
<fieldset>
	{{Form::text('telephone_number', $telephones->telephone_number, array('placeholder' => '4567890'))}}
</fieldset>
<fieldset>
	{{Form::submit()}}
</fieldset>

app/views/telephones/create.blade.php
@extends('theme')

@section('title') Nuevo Contacto @stop

@section('header_title') Nuevo Contacto @stop

@section('content')
	{{Form::open(array('route' => 'telephones.store', 'method' => 'POST'))}}
	@include('telephones._form')
	{{Form::close()}}
@stop

app/views/telephones/edit.blade.php
@extends('theme')

@section('title') Edición de contacto {{$contact->name}} @stop

@section('header_title') Editando perfil de {{$contact->name}} {{$contact->lastname}} @stop

@section('content')
	{{Form::open(array('route' => array('contacts.update', $contact->id), 'method' => 'PUT'))}}
	@include('contacts._form')
	{{Form::close()}}
@stop

app/views/telephones/index.blade.php
@extends('theme')

@section('title') Lista de contacts @stop

@section('header')
	@parent
	<h2>Bienvenido</h2>
@stop

@section('header_title') Lista de contacts @stop

@section('content')
<style>
	th,td{
		padding: 3px;
		border: solid #000 1px;
	}
</style>
	@if(! $telephones->isEmpty())
		<table style="border">
			<thead>
				<tr>
					<th>id</th>
					<th>publicado por</th>
					<th>Nombre</th>
					<th>email</th>
					<th>address</th>
					<th>created_at</th>
					<th>updated_at</th>
					<th>Acciones</th>
				</tr>
			</thead>
			<tbody>
			@foreach($telephone as $telephone)
				<tr>
					<td>{{$telephones->id}}</td>
					<td>{{$telephones->user->name}}</td>
					<td>{{$telephones->contacts->name}}</td>
					<td>{{$telephones->contacts->last_name}}</td>
					<td>{{$telephones->label}}</td>
					<td>{{$telephones->telephone_number}}</td>
					<td>{{$telephones->created_at}}</td>
					<td>{{$telephones->updated_at}}</td>					
					<td>
						<a href="{{route('contacts.show', array($contacts->id))}}">Ver</a>
						<a href="{{route('contacts.edit', array($contacts->id))}}">Editar</a>
					</td>					
				</tr>
			@endforeach
			</tbody>
		</table>
	@else 
		<p>No hay contacts</p>
	@endif
	<a href="{{route('telephones.create')}}">+ Nuevo contacts</a>
@stop

app/views/telephones/show.blade.php
@extends('theme')

@section('title') {{{$contact->name}}} {{{$contact->last_name}}} @stop

@section('header')
	@parent
	<h2>Contacto de: <a href="{{route('users.show', ['id' => $contact->user->id])}}">{{{$contact->user->name}}}</a></h2>
	<h3>El día: {{$contact->created_at}}</h3>
@stop

@section('header_title') contact Nro. {{$contact->id}} @stop

@section('content')
<article>
	<p style="font-size: 1em">{{{$contact->name}}}</p>
	<p style="font-size: 1em">{{{$contact->last_name}}}</p>
	<p style="font-size: 1em">{{{$contact->email}}}</p>
	<p style="font-size: 1em">{{{$contact->address}}}</p>
</article>
@stop